name: quick_math
description: The Math Vibe — Premium mental arithmetic app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  path_provider: ^2.1.4
  webview_flutter: ^4.4.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/words/synonyms.json
    - assets/words/antonyms.json
    - assets/words/spell_check.json
    - assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"    